// Shared product data for the store and product pages

export interface Product {
  id: string
  name: string
  price: number
  category: string
  artist: string
  image: string
  images?: string[]
  description?: string
  featured?: boolean
  colors?: string[]
  sizes?: string[]
  format?: string
  tracks?: number
  inStock?: boolean
  artistCut?: number
  sales?: number
  rating?: number
  reviews?: number
}

export const PRODUCTS: Product[] = [
  {
    id: 'book-tiigh',
    name: 'There It Is, Here It Go',
    price: 25,
    category: 'Book',
    artist: 'O D Porter',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800',
    featured: true,
    description: 'A powerful memoir from O D Porter — raw, honest, and deeply personal. The story of an artist from St. Louis who refused to quit.',
    inStock: true,
    artistCut: 20,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-nfc-wristband',
    name: 'Artist NFC Wristband',
    price: 15,
    category: 'Tech',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800',
    featured: true,
    description: 'Tap in to visit the artist page. Reusable NFC wristband — wear it, tap it, share the experience.',
    inStock: true,
    artistCut: 12,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-nfc-tag',
    name: 'Artist NFC Tag (Set of 3)',
    price: 12,
    category: 'Tech',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1618401471353-b98af5f8b545?w=800',
    featured: true,
    description: 'Stick anywhere. Tap in with your phone to discover the artist. Set of 3 tags.',
    inStock: true,
    artistCut: 9.60,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-nfc-card',
    name: 'Artist NFC Card',
    price: 8,
    category: 'Tech',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=800',
    description: 'Wallet-sized. Tap in to follow the artist.',
    inStock: true,
    artistCut: 6.40,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-tee-classic-black',
    name: 'Porterful Classic Tee',
    price: 28,
    category: 'Apparel',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    featured: true,
    description: 'Premium cotton tee. Show your support for independent artists.',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    artistCut: 22.40,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-hoodie-classic-black',
    name: 'Porterful Classic Hoodie',
    price: 55,
    category: 'Apparel',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    description: 'Heavyweight hoodie with embroidered Porterful logo.',
    colors: ['Black', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    artistCut: 44,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-mug-11oz-black',
    name: 'Porterful Mug',
    price: 18,
    category: 'Home',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800',
    description: '11oz ceramic mug. Start your morning with intention.',
    inStock: true,
    artistCut: 14.40,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-canvas-16x20',
    name: 'Porterful Canvas',
    price: 55,
    category: 'Art',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1549497538-303791108f95?w=800',
    description: '16x20 gallery canvas. Made to last.',
    inStock: true,
    artistCut: 44,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'odp-poster-18x24',
    name: 'Porterful Poster',
    price: 22,
    category: 'Art',
    artist: 'Various Artists',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    description: '18x24 premium poster print.',
    inStock: true,
    artistCut: 17.60,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'ambiguous-tee',
    name: 'Ambiguous Tour Tee',
    price: 28,
    category: 'Merch',
    artist: 'O D Porter',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    featured: true,
    description: 'Premium cotton tee from the Ambiguous tour. Limited edition.',
    colors: ['Black', 'White', 'Orange'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    artistCut: 22.40,
    sales: 142,
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 'ambiguous-hoodie',
    name: 'Ambiguous Hoodie',
    price: 65,
    category: 'Merch',
    artist: 'O D Porter',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    description: 'Heavyweight hoodie with embroidered Ambiguous logo.',
    colors: ['Black', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    artistCut: 52,
    sales: 78,
    rating: 4.9,
    reviews: 45,
  },
  {
    id: 'ambiguous-vinyl',
    name: 'Ambiguous Vinyl',
    price: 35,
    category: 'Music',
    artist: 'O D Porter',
    image: 'https://images.unsplash.com/photo-1539185441755-7697f0f1e3ee?w=800',
    featured: true,
    description: 'Limited edition vinyl. 180g audiophile quality. 21 tracks from the Ambiguous album.',
    format: '12" Vinyl',
    tracks: 21,
    inStock: true,
    artistCut: 28,
    sales: 234,
    rating: 5.0,
    reviews: 67,
  },
  {
    id: 'mettle',
    name: 'METTLE - Do It With a Smile',
    price: 40,
    category: 'Merch',
    artist: 'Nikee Turbo',
    image: '/artists/nikee-turbo/products/mettle/IMG_4415.jpg',
    images: [
      '/artists/nikee-turbo/products/mettle/IMG_4413.jpg',
      '/artists/nikee-turbo/products/mettle/IMG_4414.jpg',
      '/artists/nikee-turbo/products/mettle/IMG_4415.jpg',
      '/artists/nikee-turbo/products/mettle/IMG_4416.jpg',
      '/artists/nikee-turbo/products/mettle/IMG_4417.jpg',
      '/artists/nikee-turbo/products/mettle/IMG_4418.jpg',
    ],
    featured: true,
    description: 'Premium METTLE shirt by Nikee Turbo. Do It With a Smile.',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    artistCut: 32,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
  {
    id: 'gune-shirt',
    name: 'Gune Classic Tee',
    price: 40,
    category: 'Merch',
    artist: 'Gune',
    image: '/artists/gune/gune-shirt.jpg',
    featured: true,
    description: 'Official Gune merch. Limited edition shirt.',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    artistCut: 32,
    sales: 0,
    rating: 0,
    reviews: 0,
  },
]

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id)
}

export const FEATURED_PRODUCTS = PRODUCTS.filter(p => p.featured)
