// Trending Dropshipping Products 2026
// High-margin products research from multiple sources

export const TRENDING_PRODUCTS = [
  // === WELLNESS (30-55% margins) ===
  {
    id: 'red-light-therapy-mask',
    name: 'Red Light Therapy Face Mask',
    description: 'Spa-grade results at home. Replaces $150 facial treatments.',
    category: 'wellness',
    subcategory: 'Skincare',
    basePrice: 22,
    price: 69.99,
    images: ['https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=500'],
    rating: 4.6,
    reviews: 234,
    inStock: true,
    tags: ['wellness', 'spa', 'skincare', 'trending'],
    margin: 55,
  },
  {
    id: 'posture-corrector-smart',
    name: 'Smart Posture Corrector',
    description: 'Vibrates when posture slips. Remote work ergonomics essential.',
    category: 'wellness',
    subcategory: 'Ergonomics',
    basePrice: 10,
    price: 39.99,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
    rating: 4.4,
    reviews: 189,
    inStock: true,
    tags: ['wellness', 'ergonomics', 'office', 'trending'],
    margin: 65,
  },
  {
    id: 'acupressure-mat-set',
    name: 'Acupressure Mat & Pillow Set',
    description: 'Replaces $80 massage therapy sessions. Search volume up 180%.',
    category: 'wellness',
    subcategory: 'Massage',
    basePrice: 15,
    price: 55.99,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
    rating: 4.5,
    reviews: 312,
    inStock: true,
    tags: ['wellness', 'massage', 'stress relief', 'trending'],
    margin: 60,
  },
  {
    id: 'gua-sha-stone-set',
    name: 'Gua Sha Stone Set (Jade)',
    description: 'High perceived value. Pairs with face oils for repeat purchases.',
    category: 'wellness',
    subcategory: 'Skincare',
    basePrice: 4,
    price: 28.99,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500'],
    rating: 4.7,
    reviews: 456,
    inStock: true,
    tags: ['wellness', 'skincare', 'beauty', 'trending'],
    margin: 80,
  },
  {
    id: 'infrared-heating-pad',
    name: 'Infrared Heating Pad',
    description: 'App-controlled timer. Alternative to chiropractor visits.',
    category: 'wellness',
    subcategory: 'Pain Relief',
    basePrice: 18,
    price: 65.99,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
    rating: 4.6,
    reviews: 178,
    inStock: true,
    tags: ['wellness', 'pain relief', 'heating', 'trending'],
    margin: 55,
  },
  {
    id: 'lymphatic-massager',
    name: 'Lymphatic Drainage Massager',
    description: 'Wellness trend tied to inflammation reduction.',
    category: 'wellness',
    subcategory: 'Massage',
    basePrice: 10,
    price: 38.99,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
    rating: 4.3,
    reviews: 145,
    inStock: true,
    tags: ['wellness', 'massage', 'lymphatic', 'trending'],
    margin: 65,
  },
  {
    id: 'eye-massage-mask',
    name: 'Eye Massage Mask (Heat + Vibration)',
    description: 'Screen fatigue relief for gamers, programmers, content creators.',
    category: 'wellness',
    subcategory: 'Eye Care',
    basePrice: 16,
    price: 55.99,
    images: ['https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=500'],
    rating: 4.5,
    reviews: 223,
    inStock: true,
    tags: ['wellness', 'eye care', 'gaming', 'trending'],
    margin: 55,
  },

  // === EMOTIONAL SUPPORT HOME DECOR (40-65% margins) ===
  {
    id: 'weighted-dinosaur-plushie',
    name: 'Weighted Dinosaur Plushie',
    description: 'Emotional support dinosaur. 300% search spike in late 2025.',
    category: 'home',
    subcategory: 'Decor',
    basePrice: 10,
    price: 38.99,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'],
    rating: 4.8,
    reviews: 567,
    inStock: true,
    tags: ['home', 'decor', 'comfort', 'trending'],
    margin: 65,
  },
  {
    id: 'galaxy-projector',
    name: 'Galaxy Projector (App-Controlled)',
    description: 'Creates calming atmosphere. Strong visual appeal for social media.',
    category: 'home',
    subcategory: 'Lighting',
    basePrice: 18,
    price: 59.99,
    images: ['https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=500'],
    rating: 4.6,
    reviews: 412,
    inStock: true,
    tags: ['home', 'lighting', 'projector', 'trending'],
    margin: 55,
  },
  {
    id: 'sunset-lamp',
    name: 'Sunset Lamp (Color-Changing)',
    description: 'Affordable mood lighting. Instagram aesthetic must-have.',
    category: 'home',
    subcategory: 'Lighting',
    basePrice: 14,
    price: 45.99,
    images: ['https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=500'],
    rating: 4.5,
    reviews: 389,
    inStock: true,
    tags: ['home', 'lighting', 'mood', 'trending'],
    margin: 60,
  },
  {
    id: 'flame-oil-diffuser',
    name: 'Flame Effect Essential Oil Diffuser',
    description: 'Multi-sensory experience. Sell essential oils for repeat revenue.',
    category: 'home',
    subcategory: 'Aromatherapy',
    basePrice: 20,
    price: 69.99,
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500'],
    rating: 4.4,
    reviews: 267,
    inStock: true,
    tags: ['home', 'aromatherapy', 'diffuser', 'trending'],
    margin: 55,
  },
  {
    id: 'diatomite-bath-mat',
    name: 'Diatomite Bath Mat (Super-Absorbent)',
    description: 'Solves wet bathroom floor problem. Eco-friendly. Gift-worthy.',
    category: 'home',
    subcategory: 'Bath',
    basePrice: 10,
    price: 36.99,
    images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500'],
    rating: 4.6,
    reviews: 334,
    inStock: true,
    tags: ['home', 'bath', 'eco', 'trending'],
    margin: 62,
  },

  // === CONSUMABLES FOR REPEAT REVENUE (30-50% margins) ===
  {
    id: 'silicone-air-fryer-liners',
    name: 'Silicone Air Fryer Liners (Set of 2)',
    description: 'Gets dirty, needs replacement. Air fryer ownership at all-time high.',
    category: 'kitchen',
    subcategory: 'Accessories',
    basePrice: 4,
    price: 18.99,
    images: ['https://images.unsplash.com/photo-1585527396378-2e21a01cfd1c?w=500'],
    rating: 4.7,
    reviews: 892,
    inStock: true,
    tags: ['kitchen', 'air fryer', 'consumable', 'trending'],
    margin: 68,
  },
  {
    id: 'reusable-makeup-pads',
    name: 'Reusable Makeup Remover Pads (Set of 10)',
    description: 'Eco-conscious. Eventually wears out for repeat buyers.',
    category: 'beauty',
    subcategory: 'Makeup',
    basePrice: 5,
    price: 22.99,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500'],
    rating: 4.5,
    reviews: 445,
    inStock: true,
    tags: ['beauty', 'makeup', 'eco', 'trending'],
    margin: 70,
  },
  {
    id: 'resistance-bands-set',
    name: 'Resistance Bands Set (Multiple Strengths)',
    description: 'Eventually lose tension. Fitness trend staying strong.',
    category: 'fitness',
    subcategory: 'Equipment',
    basePrice: 7,
    price: 28.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    rating: 4.6,
    reviews: 678,
    inStock: true,
    tags: ['fitness', 'bands', 'workout', 'trending'],
    margin: 65,
  },

  // === KITCHEN & ORGANIZATION (35-60% margins) ===
  {
    id: 'vegetable-chopper',
    name: 'Multi-Blade Vegetable Chopper',
    description: 'Time-saving. Satisfying demo videos for marketing.',
    category: 'kitchen',
    subcategory: 'Tools',
    basePrice: 10,
    price: 35.99,
    images: ['https://images.unsplash.com/photo-1585527396378-2e21a01cfd1c?w=500'],
    rating: 4.5,
    reviews: 523,
    inStock: true,
    tags: ['kitchen', 'tools', 'cooking', 'trending'],
    margin: 60,
  },
  {
    id: 'magnetic-spice-rack',
    name: 'Magnetic Spice Rack System',
    description: 'Organization + space-saving. High visual appeal.',
    category: 'kitchen',
    subcategory: 'Organization',
    basePrice: 15,
    price: 52.99,
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500'],
    rating: 4.4,
    reviews: 289,
    inStock: true,
    tags: ['kitchen', 'organization', 'spices', 'trending'],
    margin: 58,
  },
  {
    id: 'collapsible-containers',
    name: 'Collapsible Storage Containers (Set)',
    description: 'Small kitchen solutions. RV owners, apartment dwellers.',
    category: 'kitchen',
    subcategory: 'Storage',
    basePrice: 8,
    price: 28.99,
    images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500'],
    rating: 4.6,
    reviews: 412,
    inStock: true,
    tags: ['kitchen', 'storage', 'organization', 'trending'],
    margin: 65,
  },
  {
    id: 'oil-sprayer-bottle',
    name: 'Oil Sprayer Bottle (Mist Function)',
    description: 'Health-conscious cooking. Bundle with air fryer liners.',
    category: 'kitchen',
    subcategory: 'Tools',
    basePrice: 5,
    price: 22.99,
    images: ['https://images.unsplash.com/photo-1585527396378-2e21a01cfd1c?w=500'],
    rating: 4.7,
    reviews: 356,
    inStock: true,
    tags: ['kitchen', 'cooking', 'health', 'trending'],
    margin: 72,
  },
  {
    id: 'automatic-soap-dispenser',
    name: 'Automatic Soap Dispenser (Touchless)',
    description: 'Hygiene concern. Battery-operated convenience.',
    category: 'home',
    subcategory: 'Bath',
    basePrice: 10,
    price: 32.99,
    images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500'],
    rating: 4.5,
    reviews: 478,
    inStock: true,
    tags: ['home', 'bath', 'hygiene', 'trending'],
    margin: 60,
  },
  {
    id: 'silicone-stretch-lids',
    name: 'Silicone Stretch Lids (Set of 6)',
    description: 'Replaces plastic wrap. Replacement cycle creates repeat buyers.',
    category: 'kitchen',
    subcategory: 'Storage',
    basePrice: 6,
    price: 24.99,
    images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500'],
    rating: 4.8,
    reviews: 634,
    inStock: true,
    tags: ['kitchen', 'storage', 'eco', 'trending'],
    margin: 68,
  },

  // === FITNESS (40-65% margins) ===
  {
    id: 'smart-jump-rope',
    name: 'Smart Jump Rope (Counter Display)',
    description: 'Cardio in minimal space. App integration for gamification.',
    category: 'fitness',
    subcategory: 'Cardio',
    basePrice: 12,
    price: 39.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    rating: 4.4,
    reviews: 234,
    inStock: true,
    tags: ['fitness', 'cardio', 'gaming', 'trending'],
    margin: 60,
  },
  {
    id: 'yoga-mat-alignment',
    name: 'Yoga Mat with Alignment Lines',
    description: 'Beginner-friendly guidance. Thick cushioning trend.',
    category: 'fitness',
    subcategory: 'Yoga',
    basePrice: 10,
    price: 36.99,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500'],
    rating: 4.6,
    reviews: 567,
    inStock: true,
    tags: ['fitness', 'yoga', 'beginner', 'trending'],
    margin: 62,
  },
  {
    id: 'foam-roller-textured',
    name: 'Textured Foam Roller',
    description: 'Recovery tool. Replaces massage therapy.',
    category: 'fitness',
    subcategory: 'Recovery',
    basePrice: 9,
    price: 32.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    rating: 4.5,
    reviews: 389,
    inStock: true,
    tags: ['fitness', 'recovery', 'massage', 'trending'],
    margin: 65,
  },
  {
    id: 'cooling-towel-instant',
    name: 'Instant Cooling Towel',
    description: 'Summer essential. Sports/outdoor market.',
    category: 'fitness',
    subcategory: 'Accessories',
    basePrice: 4,
    price: 18.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    rating: 4.7,
    reviews: 712,
    inStock: true,
    tags: ['fitness', 'cooling', 'summer', 'trending'],
    margin: 73,
  },
  {
    id: 'doorway-pull-up-bar',
    name: 'Doorway Pull-Up Bar (No-Installation)',
    description: 'Full upper body workout. Apartment-friendly.',
    category: 'fitness',
    subcategory: 'Strength',
    basePrice: 15,
    price: 49.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    rating: 4.3,
    reviews: 267,
    inStock: true,
    tags: ['fitness', 'strength', 'apartment', 'trending'],
    margin: 58,
  },

  // === TECH ACCESSORIES ===
  {
    id: 'wireless-earbuds-pro',
    name: 'Wireless Earbuds Pro',
    description: 'Noise cancelling, 24hr battery. Customer favorite.',
    category: 'tech',
    subcategory: 'Audio',
    basePrice: 18,
    price: 49.99,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500'],
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    tags: ['tech', 'audio', 'wireless', 'trending'],
    margin: 50,
  },
  {
    id: 'phone-charger-braided',
    name: 'Braided Fast Charge Cable',
    description: 'Braided, fast charge. Everyone needs extras.',
    category: 'tech',
    subcategory: 'Chargers',
    basePrice: 4,
    price: 14.99,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500'],
    rating: 4.7,
    reviews: 2156,
    inStock: true,
    tags: ['tech', 'charger', 'cable', 'essential'],
    margin: 68,
  },
  {
    id: 'magnetic-phone-mount',
    name: 'Magnetic Phone Mount (Car)',
    description: 'Strong magnet. One-hand operation.',
    category: 'tech',
    subcategory: 'Mounts',
    basePrice: 6,
    price: 19.99,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500'],
    rating: 4.6,
    reviews: 876,
    inStock: true,
    tags: ['tech', 'car', 'mount', 'essential'],
    margin: 65,
  },
]

// Products that can be fulfilled via Printful
export const PRINTFUL_TRENDING = TRENDING_PRODUCTS.filter(p => {
  // These categories work with Printful's catalog
  return ['apparel', 'home', 'accessories', 'beauty'].includes(p.category)
})

// Categories for filtering
export const TRENDING_CATEGORIES = [
  { id: 'wellness', name: 'Wellness', icon: '💆', margin: '30-55%' },
  { id: 'home', name: 'Home & Decor', icon: '🏠', margin: '40-65%' },
  { id: 'kitchen', name: 'Kitchen', icon: '🍳', margin: '35-60%' },
  { id: 'fitness', name: 'Fitness', icon: '💪', margin: '40-65%' },
  { id: 'tech', name: 'Tech', icon: '📱', margin: '35-55%' },
  { id: 'beauty', name: 'Beauty', icon: '💄', margin: '40-70%' },
]
